### ISSUE TITLE
Offset used to retrieve an item from a collection was out of range

### ISSUE THREAD

**Issue by vishakha-b** [51Degrees/device-detection-php-onpremise#1] opened 2021-06-19 10:41 UTC
Getting below error intermittently : 
Offset used to retrieve an item from a collection was out of range

We are getting an error from 51 Degrees on-premise library, occurrence is very high

User Agent : Mozilla/5.0 (Linux; Android 11; SM-G780F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

![image](https://user-images.githubusercontent.com/18513190/122639787-7d35d680-d119-11eb-8df5-ba2b05a127c1.png)

Please help

**Comment by ben51degrees** [comment] 2021-06-23 13:39
Hi @vishakha-b ,
I can't manage to recreate this no matter how much I throw at it. Could you let me know if you're using the latest commit, and provide some example code along with the requests you're making in order to recreate?

Could you also confirm that you're able to run the gettingstarted example without issue?

Thanks,
Ben.

**Comment by vishakha-b** [comment] 2021-06-29 04:39
Hi @ben51degrees ,

We are using latest commit and we can successfully run gettingstarted example without any issue.
But from our application where we have integrated 51 degrees there we intermittently get the error which I have mentioned earlier in the thread from one of the server.

We had gotten below error while installing 51 degrees on that server in the **make** step.

![image](https://user-images.githubusercontent.com/18513190/123737615-e7403f80-d8c0-11eb-927e-4ade81356bde.png)

So we copied **so** file to this server from the server where it installed without any error.

The server where we installed 51 degrees without any error we are not getting the issue but where we have gotten error while installing and copied **so** file from different server, we are getting error there.

Help me with the installation issue it might resolve the problem.

Let me know if you want any further details.

**Comment by ben51degrees** [comment] 2021-07-07 12:12
Hi @vishakha-b ,
Apologies for the slow response.
It looks like the problem is with the GCC version you're using. Which version of GCC is installed on the machine which does not compile? The overflow builtins which are causing the compilation errors are not available in GCC 4, for that you will need GCC 5 or above - see C/C++ in our [version support page](https://51degrees.com/documentation/4.2/_info__version_support.html).

I would expect the runtime errors you were seeing when copying executable from the machine with a different compiler if this is the case, as there will be C libraries that may not be installed on the target machine.

Thanks,
Ben.

**Comment by ben51degrees** [comment] 2021-07-07 12:16
For a bit of extra info, see the section on `__builtin_add_overflow` in the [GCC 5 changes](https://gcc.gnu.org/gcc-5/changes.html)

**Comment by ben51degrees** [comment] 2021-09-03 10:50
Hi @vishakha-b ,
I assume this has solved the issue for you? I'll close this, but if it's still a problem, feel free to reopen and let me know.

**Comment by vishakha-b** [comment] 2021-09-17 09:12
Hi Ben,

Thanks for previous response.
I am reopening the ticket again as after successful installation also we are getting this error.
Details of the error. 
![image](https://user-images.githubusercontent.com/18513190/133756569-d3c6399b-94f4-4ed2-92de-312badccbdf4.png)

we have below gcc version on server.

![image](https://user-images.githubusercontent.com/18513190/133756950-afc33574-d229-4d60-bb7f-6b383c35a3cf.png)

We successfully ran gettingstarted.php as well.
![image](https://user-images.githubusercontent.com/18513190/133757017-1ac793ee-94ab-4bb8-b09e-6fdaafb33fc8.png)

Please help us here to solve as after the successful installation as well we are intermittently getting this error.

**Comment by vishakha-b** [comment] 2021-09-21 05:16
@ben51degrees please update

**Comment by fatima51Degrees** [comment] 2021-09-21 08:44
Hi vishakha-b,

 
Can you please share the bit of code where you're calling the 51Degrees API in order to regenerate?

**Comment by vishakha-b** [comment] 2021-09-22 07:24
Hi @fatima51Degrees ,
Please find code.

Object of class : 

![image](https://user-images.githubusercontent.com/18513190/134300348-6828db91-a711-4764-aa1f-8aa7e29d0bf6.png)

class : 

![image](https://user-images.githubusercontent.com/18513190/134300451-d1a84449-e9ec-4394-afc1-b7452742d930.png)

Let us know if you need any further details.

**Comment by vishakha-b** [comment] 2021-09-24 07:00
@fatima51Degrees any update on this?
any more details required from our end?

**Comment by fatima51Degrees** [comment] 2021-09-24 08:16
Hi  vishakha-b,

Thanks for providing the information. I will get back to you with an update in the next week.

**Comment by vishakha-b** [comment] 2021-09-30 10:52
Hi @fatima51Degrees,

Any update?

**Comment by Joseph51D** [comment] 2021-10-01 09:04
Hi @vishakha-b 

I've not been able to recreate the issue so far.

Can you confirm which version of code you are using? It's worth checking you're using the latest version of this repo and also make sure any git submodules within are up-to-date. It appears you are using an older version of the common-cxx repo which is nested within this one.

Regards,
Joseph

**Comment by fatima51Degrees** [comment] 2021-10-07 16:48
Hi @vishakha-b

I've not been able to recreate the issue yet again even with the code file and user-agent list that you have shared in an email.

Have you used our make file to build the extension? Can you please share all the build steps?

Regards,
Fatima

**Comment by fatima51Degrees** [comment] 2021-10-11 08:54
Hi @vishakha-b,

Thank you for your response. Unfortunately, We have not been able to recreate the issue on Ubuntu-18.04 with your provided code. We only test it on Ubuntu in Continuous Integration as Microsoft does not provide any RedHat based VM. I'm now going to setup this up locally on RedHat based Linux Distribution to check if there is something with the Operating System, and will let you know in next few days. Meanwhile can you please confirm the details/version of the operating system you are running this example on?

**Comment by fatima51Degrees** [comment] 2021-11-01 15:12
Hi vishakha-b,

We will close this ticket for now. Please feel free to reopen it if you still experience the same problem. If you choose to reopen it, please add a full video of the process so we can diagnose the issue.

Regards,
Fatima

**Comment by vishakha-b** [comment] 2021-11-25 17:51
Hi Fatima,

We had taken the fresh amazon linux machine c5.xlarge where we installed 51 degrees (attaching [video](https://www.awesomescreenshot.com/video/6159630?key=d5801e871fa586ad154757f97cfcfe67) for same).
Also we successfully ran the gettingstarted.php and script which was shared by you on 13th Oct. (attaching [video](https://www.awesomescreenshot.com/video/6159750?key=2e2dd8976a5f554a1e075244c0881010) for same)

We performed load test with 4 concurrent users for 30 min.
We have seen that out of 376854 total requests 77% requests have received an exception.
Let me know if you want to share details over email.

**Comment by jwrosewell** [comment] 2021-11-25 18:11
Thank you for sharing this.

Can you verify what you mean by "an exception"?

Looking at the second video it looks like the value is not a valid User-Agent. See the following image where the string value contains escape characters like %2F. The value presented for device detection must appear is it left the device without alteration if device detection is to work effectively.

![image](https://user-images.githubusercontent.com/1679482/143486505-a5fc80e8-84e0-4a46-94a8-d5e805bd946b.png)

**Comment by vishakha-b** [comment] 2021-11-29 11:47
Hi @jwrosewell ,

Please find attachment for the full trace of exception we are getting [exception.txt] (https://github.com/51Degrees/device-detection-php-onpremise/files/7616829/exception.txt)

Please note that the CSV we shared earlier was created with intention of using it with performance testing through Jmeter over HTTP. With Jmeter the user agent from the csv is passed as is in a request query parameter(not in the request header) hence it is intentionally url encoded.

The log seen in the second video which is through the php file offset-issue.txt (renamed to .php) is a sample provide by your collegue Fatima. It appears that she has used our URL encoded csv directly without any URL decoding.

However the file we have used for performance test on our web server uses a decoded version of the user agent. Please find the sample of the php file we used for performance testing [51degrees-code-used-for-performance-testing.txt] (https://github.com/51Degrees/device-detection-php-onpremise/files/7616476/51degrees-code-used-for-performance-testing.txt). 

For your convenience I am furnishing the details again,

1) We have run the performance test with the file mentioned above i.e 51degrees-code-used-for-performance-testing.txt (renamed to .php)
2) We performed load test with 4 concurrent users for 30 min
3) We have seen that out of 376854 total requests, 77% requests have received an exception
4) Details of the machine used for performance test as as follow,
	NAME="Amazon Linux"
	VERSION="2"
	ID="amzn"
	ID_LIKE="centos rhel fedora"
	VERSION_ID="2"
	PRETTY_NAME="Amazon Linux 2"
	HOME_URL="https://amazonlinux.com/"
    INSTANCE TYPE = "c5.xlarge" (4 core, 8 GB) 

We have a video of the preformance test but its quite large (about 400mb) to attach hence we have extracted the exception and share in text file i.e exception.txt. Let me know if you need video, we fill find a way to share.

**Comment by jwrosewell** [comment] 2021-11-29 11:51
Thank you for the additional detail. We will analyze over the next couple of days and report out findings.

**Comment by tungntpham** [comment] 2021-11-30 10:16
Hi @vishakha-b,

We have reviewed the sample of the performance test that you provided and there are a few things we would like to suggest:
- There are a few bugs in the file:
  -  In function `getBrand`, the `$capability` variable was spelled incorrectly so you have seen `undefined variable` error from your console log.
  - In function `getDeviceForUserAgent`, the `device` object was obtained from incorrect source. It should be obtained from the `$this->resultObj` instead of `$flowData`.
- We also suggest that you only create the `$pipeline` object once in the constructor, instead of the `getDeviceForUserAgent`. The reason is that, each time the `$pipeline` object is created, it would cause the data file to be loaded, which would then potentially result in out of memory eventually.

I have attached an updated version of your performance test sample ([performance-testing.txt](https://github.com/51Degrees/device-detection-php-onpremise/files/7624890/performance-testing.txt)). Please give another try and also make sure that the data file that you are using has `hardwarevendor` property included.

Many thanks,
Tung.

**Comment by tungntpham** [comment] 2021-11-30 10:38
Hi @vishakha-b,

Would you also provide us your sample decoded User-Agents test file, please? We would like to see if we could reproduce the issue in our test environment.

Many thanks,
Tung.

**Comment by vishakha-b** [comment] 2021-11-30 13:43
Hi @tungntpham ,

Thanks for reply.
We will try out the changes you suggested and update.

Please find attachment for the decode user agent csv as requested by you.
[decodeUA-51degreesTeam.csv](https://github.com/51Degrees/device-detection-php-onpremise/files/7626125/decodeUA-51degreesTeam.csv)

**Comment by tungntpham** [comment] 2021-11-30 14:12
Thanks @vishakha-b,

Tung.

**Comment by vishakha-b** [comment] 2021-12-03 13:36
Hi @tungntpham ,

We have done the performance testing using provided performance test sample by you on the same machine.
Below are the scenarios we checked :

1) 30 min of performance testing with 1 concurrent user 
	- no exceptions found
2) 45 min of performance testing with 4 concurrent users
	- 78% of exceptions found of total requests

We are also sending the jmx file which we used to send 4 concurrent users, here we used jmeter cluster.
[51Degree_Performance_jmx.txt](https://github.com/51Degrees/device-detection-php-onpremise/files/7649958/51Degree_Performance_jmx.txt)
[OnlyUA.csv](https://github.com/51Degrees/device-detection-php-onpremise/files/7649960/OnlyUA.csv)

Also we have observed that if we get this exception, we continuously get this on single request as well till we reboot the server.
Attaching the SS.
![image](https://user-images.githubusercontent.com/18513190/144611223-b67875a2-87d3-4d63-8c53-8e93efd4c7af.png)

**Comment by tungntpham** [comment] 2021-12-13 18:07
Hi @vishakha-b,

Thank you for the details. We have now managed to reproduce the issue and are now looking to make a fix for it.

The cause of this error is due to the fact that, under high load, PHP garbage collector cannot be triggered fast enough to free all native resource that has been allocated, resulting in memory exhaustion and corrupting data which leads to this error.

Due to the nature of the issue, since it was only reproducible under high load in production environment, it wasn't possible to discover sooner in our test environment. We will look to add this configuration into our CI/CD to make sure  similar issues won't happen again.

We will update you as soon as we have a release date for the fix.

Kind regards,
Tung.

**Comment by vishakha-b** [comment] 2021-12-14 07:54
Thanks for the update @tungntpham

**Comment by tungntpham** [comment] 2021-12-14 09:04
Hi @vishakha-b,

Can you also provide us further details on your production environment, apart from the machine specification that you already provided, please? We just want to make sure that we won't miss any special settings that might impact the result. For examples:
- Web server
- How php is configured to run? php-fpm?
- Any other special options that you set for your web server?
- Any other special options that you set for you php.ini or with php-fpm if used?
- Any others that may impact how php application is run.

Many thanks,
Tung.

**Comment by tungntpham** [comment] 2021-12-16 12:47
Hi @vishakha-b,

We have narrowed down the issue to where we believe is the main cause of this problem. Based on our investigation, this problem only occurs under certain environments with performance profile set to others than HighPerformance and MaxPerformance. That means, with other profiles, where data is partially or fully loaded dynamically from disk, the data would potentially failed to be loaded correctly under extreme circumstances, resulting in the issue that being seen. This won’t happen with HighPerformance and MaxPerformance profiles since there aren’t any dynamic loading happening. Thus, we recommend that MaxPerformance profile is used in your environment to provide the best performance.

To set the performance profile, please add the following line to your php.ini:

```
FiftyOneDegreesHashEngine.performance_profile=MaxPerformance
```
Or
```
FiftyOneDegreesHashEngine.performance_profile=HighPerformance
```
Please have a try and let us know if this works for you. We will keep you updated once we release the fix for other profiles.

Many thanks,
Tung.

**Comment by ben51degrees** [comment] 2021-12-22 13:27
Closing this issue with `HighPerformance` configuration as the solution. When forked by certain process managers, the extension does not support the use of other configurations.
Documentation has been updated to give a full explanation, see https://github.com/51Degrees/device-detection-php-onpremise/tree/4.3.8#running-under-process-manager.

**Closed by ben51degrees** 2021-12-22 13:27 UTC
Labels: status: assigned
